dataset:
  train:
    name: mixed
    prob_ls: [0.5, 0.49, 0.01]
    dataset_list:
    - name: hypersim_normals
      disp_name: hypersim_normals_train
      dir: hypersim
      filenames: data_split/hypersim_normals/hypersim_filtered_all.txt
      resize_to_hw:
      - 480
      - 640
    - name: interiorverse_normals
      disp_name: interiorverse_normals_train
      dir: interiorverse/scenes_85
      filenames: data_split/interiorverse_normals/interiorverse_filtered_all.txt
      resize_to_hw: null
    - name: sintel_normals
      disp_name: sintel_normals_train
      dir: sintel
      filenames: data_split/sintel_normals/sintel_filtered.txt
      resize_to_hw:
      - 480
      - 640
      center_crop: true
